services:
  app:
    build: .
    volumes:
      - db_data:/app/data
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DATABASE_PATH=/app/data/db.sqlite
      - HOST=0.0.0.0
      - PORT=4321
    networks:
      - internal_net
    restart: unless-stopped
volumes:
  db_data:

networks:
  proxy:
    external: true
  internal_net:
    external: true
